import { defineCollection } from 'astro:content';
import { jsonProductsLoader } from './content/loaders/json-products-loader.ts';
import { productSchema } from './content/schemas/product.ts';

// Data generated by `node scripts/generate-catalog-data.mjs` from the raw supplier
// exports in `src/data/suppliers/` (gitignored). Rerun that script after a new export.
const products = defineCollection({
	loader: jsonProductsLoader({
		sources: [
			{ supplier: 'portwest', jsonPath: 'src/data/catalog/products.portwest.json' },
			{ supplier: 'mascot', jsonPath: 'src/data/catalog/products.mascot.json' },
			{ supplier: 'blaklader', jsonPath: 'src/data/catalog/products.blaklader.json' },
		],
	}),
	schema: productSchema,
});

export const collections = { products };
